image: docker:latest

services:
  - docker:dind

stages:
- build

variables:
  TAG: registry.gitlab.com/salokyn/docker-s3ql-$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $TAG .
    - docker push $TAG
