image: docker:latest

stages:
- build

variables:
  TAG: registry.gitlab.com/salokyn/docker-s3ql-$CI_COMMIT_REF_NAME

before_script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $TAG .
    - docker push $TAG
