stages:
  - shellcheck
  - build
  - test
  - publish

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

shellcheck:
  image: koalaman/shellcheck-alpine
  stage: shellcheck
  script:
    - "find . -name '*.sh' -type f -print0 | LC_ALL=C.UTF-8 xargs -n 1 -t -0 shellcheck"
  allow_failure: true

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/build-env || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/build-env --pull -t $CI_REGISTRY_IMAGE/build-env -f dockerfile_build .
    - docker push $CI_REGISTRY_IMAGE/build-env
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $IMAGE_TAG
    - docker run -e S3QL_USERNAME -e S3QL_PASSWORD -e S3QL_PROJECT -e FS_PASSPHRASE
                 -e S3QL_URL=swiftks://auth.cloud.ovh.net/GRA1:test-s3ql_2/
                 $IMAGE_TAG
                 echo yes | s3qladm delete swiftks://auth.cloud.ovh.net/GRA1:test-s3ql_2/
    - docker run -e S3QL_USERNAME -e S3QL_PASSWORD -e S3QL_PROJECT -e FS_PASSPHRASE
                 -e S3QL_URL=swiftks://auth.cloud.ovh.net/GRA1:test-s3ql_2/
                 $IMAGE_TAG
                 mkfs.s3ql --plain swiftks://auth.cloud.ovh.net/GRA1:test-s3ql_2/
    - docker run -d -e S3QL_USERNAME -e S3QL_PASSWORD -e S3QL_PROJECT -e FS_PASSPHRASE
                 -e S3QL_URL=swiftks://auth.cloud.ovh.net/GRA1:test-s3ql_2/
                 --cap-add SYS_ADMIN
                 --device /dev/fuse
                 --security-opt apparmor:unconfined
                 --name firstmount
                 $IMAGE_TAG
    - sleep 30
    - docker logs firstmount
    - test $(docker inspect -f {{.State.Running}} firstmount) = true
    - docker stop firstmount
    - docker logs firstmount
    - docker run -d -e S3QL_USERNAME -e S3QL_PASSWORD -e S3QL_PROJECT -e FS_PASSPHRASE
                 -e S3QL_URL=swiftks://auth.cloud.ovh.net/GRA1:test-s3ql_2/
                 --cap-add SYS_ADMIN
                 --device /dev/fuse
                 --security-opt apparmor:unconfined
                 --name secondmount
                 $IMAGE_TAG
    - sleep 30
    - docker logs secondmount
    - test $(docker inspect -f {{.State.Running}} secondmount) = true
    - docker stop secondmount
    - docker logs secondmount


publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login -u salokyn -p $DOCKER_PASSWORD
  script:
    - docker pull $IMAGE_TAG
    - VERSION=$(docker run registry.gitlab.com/salokyn/docker-s3ql s3qlstat --version|awk '{print $2}')
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:$VERSION
    - docker tag $IMAGE_TAG salokyn/docker-s3ql:latest
    - docker tag $IMAGE_TAG salokyn/docker-s3ql:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push salokyn/docker-s3ql:latest
    - docker push salokyn/docker-s3ql:$VERSION
  only:
    - master
  
